/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedCanaisRouteImport } from './routes/_authenticated/canais'
import { Route as AuthenticatedFilmesRouteImport } from './routes/_authenticated/filmes'
import { Route as AuthenticatedSeriesRouteImport } from './routes/_authenticated/series'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCanaisRoute = AuthenticatedCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmesRoute = AuthenticatedFilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeriesRoute = AuthenticatedSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canais': typeof AuthenticatedCanaisRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/series': typeof AuthenticatedSeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canais': typeof AuthenticatedCanaisRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/series': typeof AuthenticatedSeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/canais': typeof AuthenticatedCanaisRoute
  '/_authenticated/filmes': typeof AuthenticatedFilmesRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/canais' | '/filmes' | '/series'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/canais' | '/filmes' | '/series'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/canais'
    | '/_authenticated/filmes'
    | '/_authenticated/series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/canais': {
      id: '/_authenticated/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof AuthenticatedCanaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filmes': {
      id: '/_authenticated/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof AuthenticatedFilmesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCanaisRoute: typeof AuthenticatedCanaisRoute
  AuthenticatedFilmesRoute: typeof AuthenticatedFilmesRoute
  AuthenticatedSeriesRoute: typeof AuthenticatedSeriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCanaisRoute: AuthenticatedCanaisRoute,
  AuthenticatedFilmesRoute: AuthenticatedFilmesRoute,
  AuthenticatedSeriesRoute: AuthenticatedSeriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
