/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DonoRouteImport } from './routes/dono'
import { Route as AuthenticatedCanaisRouteImport } from './routes/_authenticated/canais'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedFilmesRouteImport } from './routes/_authenticated/filmes'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSeriesRouteImport } from './routes/_authenticated/series'
import { Route as AuthenticatedServidoresRouteImport } from './routes/_authenticated/servidores'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as TesteSlugRouteImport } from './routes/teste.$slug'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as ApiPublicLegacyCssRouteImport } from './routes/api/public/legacy-css'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DonoRoute = DonoRouteImport.update({
  id: '/dono',
  path: '/dono',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCanaisRoute = AuthenticatedCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmesRoute = AuthenticatedFilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeriesRoute = AuthenticatedSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServidoresRoute = AuthenticatedServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TesteSlugRoute = TesteSlugRouteImport.update({
  id: '/teste/$slug',
  path: '/teste/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLegacyCssRoute = ApiPublicLegacyCssRouteImport.update({
  id: '/api/public/legacy-css',
  path: '/api/public/legacy-css',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dono': typeof DonoRoute
  '/canais': typeof AuthenticatedCanaisRoute
  '/conta': typeof AuthenticatedContaRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/series': typeof AuthenticatedSeriesRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/teste/$slug': typeof TesteSlugRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/legacy-css': typeof ApiPublicLegacyCssRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dono': typeof DonoRoute
  '/canais': typeof AuthenticatedCanaisRoute
  '/conta': typeof AuthenticatedContaRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/series': typeof AuthenticatedSeriesRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/teste/$slug': typeof TesteSlugRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/legacy-css': typeof ApiPublicLegacyCssRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/dono': typeof DonoRoute
  '/_authenticated/canais': typeof AuthenticatedCanaisRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/filmes': typeof AuthenticatedFilmesRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRoute
  '/_authenticated/servidores': typeof AuthenticatedServidoresRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/teste/$slug': typeof TesteSlugRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/legacy-css': typeof ApiPublicLegacyCssRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dono'
    | '/canais'
    | '/conta'
    | '/filmes'
    | '/inicio'
    | '/painel'
    | '/series'
    | '/servidores'
    | '/suporte'
    | '/usuarios'
    | '/teste/$slug'
    | '/api/public/image'
    | '/api/public/legacy-css'
    | '/api/public/mercadopago-webhook'
    | '/api/public/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dono'
    | '/canais'
    | '/conta'
    | '/filmes'
    | '/inicio'
    | '/painel'
    | '/series'
    | '/servidores'
    | '/suporte'
    | '/usuarios'
    | '/teste/$slug'
    | '/api/public/image'
    | '/api/public/legacy-css'
    | '/api/public/mercadopago-webhook'
    | '/api/public/stream'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dono'
    | '/_authenticated/canais'
    | '/_authenticated/conta'
    | '/_authenticated/filmes'
    | '/_authenticated/inicio'
    | '/_authenticated/painel'
    | '/_authenticated/series'
    | '/_authenticated/servidores'
    | '/_authenticated/suporte'
    | '/_authenticated/usuarios'
    | '/teste/$slug'
    | '/api/public/image'
    | '/api/public/legacy-css'
    | '/api/public/mercadopago-webhook'
    | '/api/public/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DonoRoute: typeof DonoRoute
  TesteSlugRoute: typeof TesteSlugRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
  ApiPublicLegacyCssRoute: typeof ApiPublicLegacyCssRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dono': {
      id: '/dono'
      path: '/dono'
      fullPath: '/dono'
      preLoaderRoute: typeof DonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/canais': {
      id: '/_authenticated/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof AuthenticatedCanaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filmes': {
      id: '/_authenticated/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof AuthenticatedFilmesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servidores': {
      id: '/_authenticated/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof AuthenticatedServidoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/teste/$slug': {
      id: '/teste/$slug'
      path: '/teste/$slug'
      fullPath: '/teste/$slug'
      preLoaderRoute: typeof TesteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/legacy-css': {
      id: '/api/public/legacy-css'
      path: '/api/public/legacy-css'
      fullPath: '/api/public/legacy-css'
      preLoaderRoute: typeof ApiPublicLegacyCssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCanaisRoute: typeof AuthenticatedCanaisRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedFilmesRoute: typeof AuthenticatedFilmesRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSeriesRoute: typeof AuthenticatedSeriesRoute
  AuthenticatedServidoresRoute: typeof AuthenticatedServidoresRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCanaisRoute: AuthenticatedCanaisRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedFilmesRoute: AuthenticatedFilmesRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSeriesRoute: AuthenticatedSeriesRoute,
  AuthenticatedServidoresRoute: AuthenticatedServidoresRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DonoRoute: DonoRoute,
  TesteSlugRoute: TesteSlugRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
  ApiPublicLegacyCssRoute: ApiPublicLegacyCssRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
